handle: Abstract idea for a process
type: input-output
description: A well defined idea for how a process should be handled
required:
  - Process steps
  - Process inputs and outputs
optional:
---
handle: Convert process steps into transformers
type: transformer
description: The process should be expressed with simple transformations
actor: Process owner
access:
  - GitHub account
  - access to 'https://github.com/product-os'
input:
  - Abstract idea for a process
output:
  - Process simplified yaml file
instructions: "1. Every step in a process has an input, which after a set of instructions (transformation) becomes an output. The output will become an input for the next step which is a new transformation.

2. The first step is to define what transformations are required, what are the inputs and outputs of each transformation

3. To define an input or an output you can use the 'input-output' element.

4. To define a transformer you can use the 'transformer' element

5. Instructions in a transformer are very important as they describe what exactly needs to be done during these transformation. These steps might be followed my a human being on a manual step or a machine (transformer) when a step is automated.

6. You need to write all these transformation into the 'meta.yml' file, here's a simple example of a transformer that gets the details of a team member and sends them an email with a google form:

"
---
handle: Process simplified yaml file
type: input-output
description: A yaml file that contains the process transformations
required:
  - inputs
  - transformations
  - outputs
optional:
---
handle: Convert process to a diagram
type: transformer
description: Create a high level diagram of the process
actor: GitHub CI
access:
input:
  - Process simplified yaml file
output:
  - Process diagram image
instructions: "1. Using mermaid syntax, create a shape based on the element type: Skewed rectangle for an input-output, rectangle for a transformer

2. Use the 'handle' as text for the each element

3. Draw an arrow from every 'input-output' to every `transformer` that calls it as `input`

4. Draw an arrow from every 'transformer' to every `input-output` that call as `output`

5. When the diagram is finished export a PNG file

6. Save the PNG file to the repo's output folder, name it as 'process-diagram.png'"

---
handle: Process diagram image
type: input-output
description: An image of the process flow chart
required:
  - PNG
optional:
---
handle: Convert simplified yaml to a markdown
type: transformer
description: Convert the yaml file into a landr readable markdown file
actor: GitHub CI
access:
input:
  - Process simplified yaml file
output:
  - Process markdown file
instructions: "1. Copy the yaml file

2. Replace 'handle:' with '#'

3. ..."
---
handle: Process markdown file
type: input-output
description: An image of the process flow chart
required:
  - PNG
optional:
---
handle: Convert simplified yaml to transformer compliant yaml
type: transformer
description: Convert the yaml file into a yaml code that transformers understand
actor: GitHub CI
access:
input:
  - Process simplified yaml file
output:
  - Jellyfish instance
instructions: "..."
---
handle: Jellyfish instance
type: input-output
description:
required:
  -
optional: