name: Process Processor

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - "main"
      - "master"

# We need write permissions for the repo to append a mermaid diagram in the markdown file
permissions:
  contents: write
  pull-requests: write

jobs:
  processor:
    name: Process markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: product-os/process/.github/actions/process-processor@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  flowzone:
    name: Flowzone
    uses: product-os/flowzone/.github/workflows/flowzone.yml@master
    secrets: inherit
    with:
      # Disable branch protection updates whilst testing flowzone, remove before merging
      cloudflare_website: "processes"
