name: Process Processor

on:
  workflow_call:

# We need write permissions for the repo to append a mermaid diagram in the markdown file
permissions:
  contents: write
  pull-requests: write

jobs:
  processor:
    name: Process markdown
    runs-on: ubuntu-latest
    steps:
      - uses: product-os/process/.github/actions/process-processor@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
