name: Process processor
on:
  workflow_call

# We need write permissions for the repo to append a mermaid diagram in the markdown file
permissions:
  contents: write

jobs:
  processor:
    uses: ./.github/actions/process-processor@latest
